// Actions get all pokemons
export const GET_ALL_POKEMONS = "GET_ALL_POKEMONS";
export const IS_LOADING_ALL_POKEMONS = "IS_LOADING_ALL_POKEMONS";
export const ERROR_ALL_POKEMONS = "ERROR_ALL_POKEMONS";

// Actions get create pokemons by...
export const GET_CREATE_POKEMONS_BY = "GET_CREATE_POKEMONS_BY";
export const IS_LOADING_CREATE_POKEMONS_BY = "IS_LOADING_CREATE_POKEMONS_BY";
export const ERROR_CREATE_POKEMONS_BY = "ERROR_CREATE_POKEMONS_BY";

// Actions get pokemon by name
export const GET_POKEMON_BY_NAME = "GET_POKEMON_BY_NAME";
export const IS_LOADING_POKEMON_NAME = "IS_LOADING_POKEMON_NAME";
export const ERROR_POKEMON_NAME = "ERROR_POKEMON_NAME";

// Actions get pokemon by type
export const GET_POKEMON_BY_TYPE = "GET_POKEMON_BY_TYPE";
export const IS_LOADING_POKEMON_TYPE = "IS_LOADING_POKEMON_TYPE";
export const ERROR_POKEMON_TYPE = "ERROR_POKEMON_TYPE";

// Actions get pokemon detail
export const GET_POKEMON_DETAIL = "GET_POKEMON_DETAIL";
export const IS_LOADING_POKEMON_DETAIL = "IS_LOADING_POKEMON_DETAIL";
export const ERROR_POKEMON_DETAIL = "ERROR_POKEMON_DETAIL";
